// Copyright Druid Mechanics
#if WITH_DEV_AUTOMATION_TESTS
#include "Misc/AutomationTest.h"
#include "Gameplay/AuraMissionAssemblyPolicy.h"
#define D55T(C,N) IMPLEMENT_SIMPLE_AUTOMATION_TEST(C,"Aura.Gameplay.Day55." N,EAutomationTestFlags::EditorContext|EAutomationTestFlags::EngineFilter)
D55T(D55Streams,"SeparateRandomStreams") bool D55Streams::RunTest(const FString&){FAuraAssemblyRandomStreams A(41),B(41);const auto E1=A.Next(EAuraAssemblyStream::Encounter);A.Next(EAuraAssemblyStream::Visual);A.Next(EAuraAssemblyStream::Visual);const auto E2=A.Next(EAuraAssemblyStream::Encounter);TestEqual(TEXT("First encounter value"),E1,B.Next(EAuraAssemblyStream::Encounter));TestEqual(TEXT("Visual consumption cannot alter encounter"),E2,B.Next(EAuraAssemblyStream::Encounter));TestEqual(TEXT("Offer untouched"),A.Counter(EAuraAssemblyStream::Offer),0);return !HasAnyErrors();}
D55T(D55Replay,"SeedDecisionReplay") bool D55Replay::RunTest(const FString&){FString E;FAuraMissionAssemblyPolicy A,B;A.Initialize(true,2,41001,TEXT("hash"),E);B.Initialize(true,2,41001,TEXT("hash"),E);for(int i=0;i<5;i++){TestEqual(TEXT("Assembly replay"),A.Streams().Next(EAuraAssemblyStream::Assembly),B.Streams().Next(EAuraAssemblyStream::Assembly));TestEqual(TEXT("Offer replay"),A.Streams().Next(EAuraAssemblyStream::Offer),B.Streams().Next(EAuraAssemblyStream::Offer));}return !HasAnyErrors();}
D55T(D55Compat,"CompatibilityRejectsBlockedEscort") bool D55Compat::RunTest(const FString&){TestFalse(TEXT("Blocked escort vent rejected"),FAuraMissionAssemblyPolicy::Compatible(TEXT("RescueRelay"),TEXT("arrangement_a"),TEXT("VolatileVents"),true,false,false));TestFalse(TEXT("Missing interaction rejected"),FAuraMissionAssemblyPolicy::Compatible(TEXT("Assault"),TEXT("arrangement_a"),TEXT("Standard"),false,true,false));TestTrue(TEXT("Valid standard accepted"),FAuraMissionAssemblyPolicy::Compatible(TEXT("Assault"),TEXT("arrangement_b"),TEXT("Standard"),false,false,false));return !HasAnyErrors();}
D55T(D55Caps,"MutatorCapsAndCounters") bool D55Caps::RunTest(const FString&){TestTrue(TEXT("Bounded patrol accepted"),FAuraMissionAssemblyPolicy::MutatorWithinCaps(TEXT("RestlessPatrols"),8,2,10,.65,true,true));TestFalse(TEXT("Live cap preserved"),FAuraMissionAssemblyPolicy::MutatorWithinCaps(TEXT("RestlessPatrols"),9,2,10,.65,true,true));TestFalse(TEXT("Cue minimum preserved"),FAuraMissionAssemblyPolicy::MutatorWithinCaps(TEXT("VolatileVents"),5,1,10,.4,true,true));TestFalse(TEXT("Both roles required"),FAuraMissionAssemblyPolicy::MutatorWithinCaps(TEXT("VolatileVents"),5,1,10,.65,true,false));return !HasAnyErrors();}
D55T(D55Consent,"PreparationBothPlayersConsent") bool D55Consent::RunTest(const FString&){FString E;FAuraMissionAssemblyPolicy P;P.Initialize(true,2,41001,TEXT("hash"),E);P.Confirm(true,TEXT("host"),true,E);TestFalse(TEXT("Host alone cannot launch"),P.CanLaunch());P.Confirm(true,TEXT("remote"),false,E);TestFalse(TEXT("Remote decline blocks changed selection"),P.CanLaunch());FAuraMissionAssemblyPolicy Q;Q.Initialize(true,2,41001,TEXT("hash"),E);Q.Confirm(true,TEXT("host"),true,E);Q.Confirm(true,TEXT("remote"),true,E);TestTrue(TEXT("Both confirmations launch"),Q.CanLaunch());return !HasAnyErrors();}
D55T(D55Matrix,"MatrixCompleteness") bool D55Matrix::RunTest(const FString&){TArray<FAuraAssemblyMatrixRow>Rows;for(int i=0;i<66;i++){FAuraAssemblyMatrixRow&R=Rows.AddDefaulted_GetRef();R.Key=FString::Printf(TEXT("row_%02d"),i);R.bMutator=i>=54;}FString E;TestTrue(TEXT("Exact 54 plus 12 matrix accepted"),FAuraMissionAssemblyPolicy::ValidateMatrix(Rows,E));Rows[65].Key=Rows[0].Key;TestFalse(TEXT("Duplicate row rejected"),FAuraMissionAssemblyPolicy::ValidateMatrix(Rows,E));Rows.RemoveAt(65);TestFalse(TEXT("Missing row rejected"),FAuraMissionAssemblyPolicy::ValidateMatrix(Rows,E));return !HasAnyErrors();}
#undef D55T
#endif
