// Copyright Druid Mechanics
#if WITH_DEV_AUTOMATION_TESTS
#include "Misc/AutomationTest.h"
#include "Gameplay/AuraBossFinaleTypes.h"
namespace D54{bool Init(FAuraBossFinaleState&S){FString E;return S.Initialize(true,FGuid(54,1,1,1),0,1200,E);} FAuraBossPatternContract Pattern(FName Id){FAuraBossPatternContract P;P.Id=Id;P.Windup=.85;P.CueLead=.65;P.Recovery=1.2;P.bAuraCounter=true;P.bBungeeCounter=true;return P;}}
#define D54T(C,N) IMPLEMENT_SIMPLE_AUTOMATION_TEST(C,"Aura.Gameplay.Day54." N,EAutomationTestFlags::EditorContext|EAutomationTestFlags::EngineFilter)
D54T(D54Phase,"PhaseCrossingOnce") bool D54Phase::RunTest(const FString&){FAuraBossFinaleState S;FString E;D54::Init(S);TestEqual(TEXT("Crossing enters phase2"),S.ObserveHealth(true,1,.49,E),EAuraBossFinaleResult::PhaseChanged);TestEqual(TEXT("Later damage does not retrigger"),S.ObserveHealth(true,2,.2,E),EAuraBossFinaleResult::NoChange);TestEqual(TEXT("One entry"),S.GetPhase2Count(),1);return !HasAnyErrors();}
D54T(D54Death,"BossDeathCancelsPendingAttack") bool D54Death::RunTest(const FString&){FAuraBossFinaleState S;FString E;D54::Init(S);S.StartAction(true,TEXT("sweep"),1,3,E);TestEqual(TEXT("Death opens extraction"),S.AcceptBossDeath(true,1,2,E),EAuraBossFinaleResult::ExtractionStarted);TestFalse(TEXT("Pending attack cancelled"),S.HasPendingAction());TestEqual(TEXT("Postmortem add rejected"),S.AdmitReinforcement(true,true,1,10,E),EAuraBossFinaleResult::Rejected);return !HasAnyErrors();}
D54T(D54Adds,"BossAddsRespectLeases") bool D54Adds::RunTest(const FString&){FAuraBossFinaleState S;FString E;D54::Init(S);TestEqual(TEXT("Failed placement admits none"),S.AdmitReinforcement(true,false,2,10,E),EAuraBossFinaleResult::NoChange);for(int i=0;i<4;i++)TestEqual(TEXT("Legal add admitted"),S.AdmitReinforcement(true,true,2+i,10,E),EAuraBossFinaleResult::AddAdmitted);TestEqual(TEXT("Fifth add rejected"),S.AdmitReinforcement(true,true,6,10,E),EAuraBossFinaleResult::Rejected);TestEqual(TEXT("Four-add cap"),S.GetAdds(),4);return !HasAnyErrors();}
D54T(D54Counter,"EveryPatternHasCounter") bool D54Counter::RunTest(const FString&){TestTrue(TEXT("Sweep counterable"),FAuraBossFinaleState::ValidatePattern(D54::Pattern(TEXT("sweep"))));auto P=D54::Pattern(TEXT("line"));P.bBungeeCounter=false;TestFalse(TEXT("Role-dependent pattern rejected"),FAuraBossFinaleState::ValidatePattern(P));P=D54::Pattern(TEXT("room"));P.bRoomWide=true;TestFalse(TEXT("Room-wide unavoidable hit rejected"),FAuraBossFinaleState::ValidatePattern(P));return !HasAnyErrors();}
D54T(D54Resource,"BossArenaResourceRecovery") bool D54Resource::RunTest(const FString&){TestTrue(TEXT("Both roles reach terminal with gates closed"),FAuraBossFinaleState::ValidateEmergencyAccess(true,true,true,false,42,42));TestFalse(TEXT("Safe-zone immunity shortcut rejected"),FAuraBossFinaleState::ValidateEmergencyAccess(true,true,true,true,42,42));TestFalse(TEXT("Cooldown reset rejected"),FAuraBossFinaleState::ValidateEmergencyAccess(true,true,true,false,42,0));return !HasAnyErrors();}
D54T(D54Race,"ExtractionRaceOneSettlement") bool D54Race::RunTest(const FString&){FString E;FAuraBossFinaleState W;D54::Init(W);W.AcceptBossDeath(true,1,100,E);TestEqual(TEXT("Accepted deaths and wipe beat completion"),W.ResolveExtractionFrame(true,103,1,false,true,E),EAuraBossFinaleResult::Failed);TestEqual(TEXT("Terminal cannot settle again"),W.ResolveExtractionFrame(true,103,0,true,true,E),EAuraBossFinaleResult::Rejected);FAuraBossFinaleState S;D54::Init(S);S.AcceptBossDeath(true,1,100,E);TestEqual(TEXT("Survivor extraction settles"),S.ResolveExtractionFrame(true,103,0,true,true,E),EAuraBossFinaleResult::Settled);TestEqual(TEXT("One settlement"),S.GetSettlementCount(),1);return !HasAnyErrors();}
D54T(D54DeadPay,"DeadTeammateEligiblePayout") bool D54DeadPay::RunTest(const FString&){FString E;FAuraBossFinaleState S;D54::Init(S);S.AcceptBossDeath(true,1,100,E);TestEqual(TEXT("Alive survivor can extract"),S.ResolveExtractionFrame(true,103,0,true,true,E),EAuraBossFinaleResult::Settled);TestEqual(TEXT("Finale emits one settlement for Day53 eligibility"),S.GetSettlementCount(),1);return !HasAnyErrors();}
#undef D54T
#endif
