// Copyright Druid Mechanics
#if WITH_DEV_AUTOMATION_TESTS
#include "Misc/AutomationTest.h"
#include "Gameplay/AuraMissionPresentationTypes.h"
#define D56T(C,N) IMPLEMENT_SIMPLE_AUTOMATION_TEST(C,"Aura.Gameplay.Day56." N,EAutomationTestFlags::EditorContext|EAutomationTestFlags::EngineFilter)
D56T(D56Revision,"SnapshotRevisionMonotonic") bool D56Revision::RunTest(const FString&){FAuraMissionPresentationState S;TestTrue(TEXT("New snapshot accepted"),S.AcceptSnapshot(2));TestFalse(TEXT("Old response rejected"),S.AcceptSnapshot(1));TestFalse(TEXT("Duplicate rejected"),S.AcceptSnapshot(2));TestEqual(TEXT("Revision stays newest"),S.GetRevision(),2);return !HasAnyErrors();}
D56T(D56Privacy,"OwnerDataNotBroadcast") bool D56Privacy::RunTest(const FString&){TestTrue(TEXT("Public payload excludes private fields"),FAuraMissionPresentationState::PayloadIsOwnerSafe(false,false,false,false));TestFalse(TEXT("Offers cannot broadcast"),FAuraMissionPresentationState::PayloadIsOwnerSafe(true,false,false,false));TestFalse(TEXT("Wallet cannot broadcast"),FAuraMissionPresentationState::PayloadIsOwnerSafe(false,false,true,false));TestTrue(TEXT("Owner payload may contain owner fields"),FAuraMissionPresentationState::PayloadIsOwnerSafe(true,true,true,true));return !HasAnyErrors();}
D56T(D56Accepted,"GuidanceRequiresAcceptedAction") bool D56Accepted::RunTest(const FString&){FAuraMissionPresentationState S;TestFalse(TEXT("Rejected action cannot complete prompt"),S.ObserveGuidance(1,false));TestEqual(TEXT("Mask unchanged"),S.GetCurrentGuidance(),uint32(0));TestTrue(TEXT("Accepted action completes prompt"),S.ObserveGuidance(1,true));return !HasAnyErrors();}
D56T(D56Durable,"GuidanceSurvivesAllowedCommits") bool D56Durable::RunTest(const FString&){FAuraMissionPresentationState S;const uint32 Legacy=S.GetLegacyTutorial();S.ObserveGuidance(1,true);TestTrue(TEXT("Normal terminal commits"),S.CommitGuidance(EAuraGuidanceCommitReason::NormalTerminal));S.ObserveGuidance(2,true);S.SimulateForcedCrash();TestEqual(TEXT("Crash restores committed bits only"),S.GetCurrentGuidance(),uint32(1));S.ObserveGuidance(4,true);TestTrue(TEXT("Forfeit commits"),S.CommitGuidance(EAuraGuidanceCommitReason::MemberForfeit));TestFalse(TEXT("Reset outside hub rejected"),S.ResetGuidanceAtHub(false));TestTrue(TEXT("Hub reset accepted"),S.ResetGuidanceAtHub(true));TestEqual(TEXT("Legacy tutorial unchanged"),S.GetLegacyTutorial(),Legacy);return !HasAnyErrors();}
D56T(D56Ping,"PingRateAndExpiry") bool D56Ping::RunTest(const FString&){FAuraMissionPresentationState S;TestTrue(TEXT("Burst one"),S.TryPing(1,0,true));TestTrue(TEXT("Burst two"),S.TryPing(2,0,true));TestTrue(TEXT("Burst three"),S.TryPing(3,0,true));TestFalse(TEXT("Burst four rejected"),S.TryPing(4,0,true));TestFalse(TEXT("Replay cannot extend TTL"),S.TryPing(1,4,true));S.PrunePings(5);TestEqual(TEXT("Markers expire at five seconds"),S.GetActivePings(),0);TestTrue(TEXT("Rate refills two per second"),S.TryPing(5,5,true));TestFalse(TEXT("Invalid range LOS rejected"),S.TryPing(6,5,false));return !HasAnyErrors();}
D56T(D56Focus,"KeyboardFocusReturns") bool D56Focus::RunTest(const FString&){FAuraMissionPresentationState S;S.OpenModal();TestFalse(TEXT("Modal owns focus"),S.HasGameplayFocus());S.CloseModal();TestTrue(TEXT("Closing restores gameplay focus"),S.HasGameplayFocus());return !HasAnyErrors();}
D56T(D56Clip,"HUDNoClipping") bool D56Clip::RunTest(const FString&){for(const auto&Size:TArray<FIntPoint>{{1280,720},{1920,1080},{2560,1440}})for(int Scale:TArray<int32>{100,125,150})TestTrue(TEXT("Required controls fit supported layout"),FAuraMissionPresentationState::ValidateHudLayout(Size.X,Size.Y,Scale,true,true,true));TestFalse(TEXT("Obscured reticle fails"),FAuraMissionPresentationState::ValidateHudLayout(1280,720,150,true,false,true));return !HasAnyErrors();}
#undef D56T
#endif
