// Copyright Druid Mechanics
#include "Gameplay/AuraMissionAssemblyPolicy.h"
uint32 FAuraAssemblyRandomStreams::Next(EAuraAssemblyStream S){const int32 I=int32(S);uint32 X=BaseSeed^(0x9E3779B9u*uint32(I+1))^uint32(++Counters[I]);X^=X<<13;X^=X>>17;X^=X<<5;return X;}
int32 FAuraAssemblyRandomStreams::Counter(EAuraAssemblyStream S)const{return Counters[int32(S)];}
bool FAuraMissionAssemblyPolicy::Initialize(bool A,int32 P,uint32 Seed,FString Hash,FString&E){E.Reset();*this=FAuraMissionAssemblyPolicy();if(!A||(P!=1&&P!=2)||Seed==0||Hash.IsEmpty()){E=TEXT("AssemblyIdentityInvalid");return false;}bAuthority=true;ParticipantCount=P;Random=FAuraAssemblyRandomStreams(Seed);return true;}
bool FAuraMissionAssemblyPolicy::Confirm(bool A,FName M,bool Accepted,FString&E){E.Reset();if(!bAuthority||!A||M.IsNone()||Confirmations.Contains(M)||Confirmations.Num()>=ParticipantCount){E=TEXT("AssemblyConsentRejected");return false;}Confirmations.Add(M,Accepted);return true;}
bool FAuraMissionAssemblyPolicy::CanLaunch()const{if(Confirmations.Num()!=ParticipantCount)return false;for(const auto&X:Confirmations)if(!X.Value)return false;return true;}
bool FAuraMissionAssemblyPolicy::Compatible(FName T,FName L,FName M,bool EscortBlocked,bool Missing,bool Small){const bool TV=T==TEXT("Assault")||T==TEXT("RescueRelay")||T==TEXT("Sabotage");const bool LV=L==TEXT("arrangement_a")||L==TEXT("arrangement_b");const bool MV=M==TEXT("Standard")||M==TEXT("RestlessPatrols")||M==TEXT("VolatileVents");return TV&&LV&&MV&&!Missing&&!Small&&!(T==TEXT("RescueRelay")&&M==TEXT("VolatileVents")&&EscortBlocked);}
bool FAuraMissionAssemblyPolicy::MutatorWithinCaps(FName M,int32 Existing,int32 Added,int32 Cap,double Cue,bool A,bool B){return (M==TEXT("RestlessPatrols")||M==TEXT("VolatileVents"))&&Existing>=0&&Added>=0&&Existing+Added<=Cap&&Cue>=.65&&A&&B;}
bool FAuraMissionAssemblyPolicy::ValidateMatrix(const TArray<FAuraAssemblyMatrixRow>&Rows,FString&E){E.Reset();if(Rows.Num()!=66){E=TEXT("AssemblyMatrixCount");return false;}TSet<FString>Seen;int32 Standard=0,Mutator=0;for(const auto&R:Rows){if(R.Key.IsEmpty()||Seen.Contains(R.Key)){E=TEXT("AssemblyMatrixDuplicate");return false;}Seen.Add(R.Key);R.bMutator?++Mutator:++Standard;}if(Standard!=54||Mutator!=12){E=TEXT("AssemblyMatrixClassCount");return false;}return true;}
