"""Apply the rollback-safe Deep AAA pass to Wuxianmen and Zhengximen.

This is an Unreal Editor Python script.  It creates a fresh multi-layer
material family, imports the additive hero-detail FBX sources generated by
GenerateGuangzhouLandmarkDeepGeometry.py, binds the new materials as Blueprint
component overrides, and mounts one visible NoCollision Nanite detail
component per gate.  Existing meshes, material siblings, maps, levels, and
collision assets are not deleted or overwritten.
"""
from __future__ import annotations

import json
from pathlib import Path

import unreal


PROJECT = Path(__file__).resolve().parents[1]
ROOT = PROJECT / "Saved/RawModelImport/V4"
DEEP_ROOT = ROOT / "DeepAAA"
SUFFIX = "_AAADeep"
MAPS = ("BaseColor", "Normal", "Roughness", "Metallic", "AO", "Height")


GATES = {
    "Wuxianmen": {
        "destination": "/Game/Assets/Environment/GuangzhouLandmarks/V4/Wuxianmen",
        "blueprint": "/Game/Assets/Environment/GuangzhouLandmarks/V4/Wuxianmen/BP_Wuxianmen_V4",
        "detail_source": DEEP_ROOT / "Wuxianmen_V4_DeepAAA.fbx",
        "detail_manifest": DEEP_ROOT / "Wuxianmen_V4_DeepAAA.json",
        "detail_folder": "/Game/Assets/Environment/GuangzhouLandmarks/V4/Wuxianmen/Meshes/DeepAAA/Wuxianmen_V4_DeepAAA",
        "detail_asset_name": "Wuxianmen_V4_DeepAAA",
        "material_names": ("WeatheredStone", "GrayBrick", "AgedWood", "GateWood", "DarkMetal", "ClayRoof", "LimePlaster", "Plaque"),
        "wuxianmen": True,
        "rollback_suffixes": ("_AAA", "_ReferenceTuned", "_AAA_Redone"),
        "detail_rotation": -90.0,
        "force_detail_reimport": True,
    },
    "Zhengximen": {
        "destination": "/Game/Assets/Environment/GuangzhouLandmarks/V4/Zhengximen",
        "blueprint": "/Game/Assets/Environment/GuangzhouLandmarks/V4/Zhengximen/BP_Zhengximen_V4",
        "detail_source": DEEP_ROOT / "Zhengximen_V4_DeepAAA.fbx",
        "detail_manifest": DEEP_ROOT / "Zhengximen_V4_DeepAAA.json",
        "detail_folder": "/Game/Assets/Environment/GuangzhouLandmarks/V4/Zhengximen/Meshes/DeepAAA/Zhengximen_V4_DeepAAA",
        "detail_asset_name": "Zhengximen_V4_DeepAAA",
        "material_names": ("GrayBrick", "StoneFoundation", "AgedWood", "DarkTimber", "ClayRoofTile", "BlackIron", "GatePlaque"),
        "wuxianmen": False,
        "rollback_suffixes": ("_AAA", "_ReferenceTuned", "_AAARedone"),
        "detail_rotation": 0.0,
        "force_detail_reimport": True,
    },
}


# Material-specific controls keep the new overlays physically plausible and
# restore separation between the light masonry, warm wood, and dark roof.
PROFILES = {
    "WeatheredStone": {"macro": (0.34, 0.38), "micro": (3.2, 3.0), "streak": (0.22, 2.8), "noise": 2.4, "variation": 0.18, "tint": (0.98, 0.96, 0.91), "dirt": (0.24, 0.20, 0.15), "edge": (1.08, 1.04, 0.92), "grime": 0.28, "streak_strength": 0.14, "edge_strength": 0.16, "roughness": 1.02, "ao": 0.88, "height": 0.038, "specular": 0.38, "clearcoat": 0.0},
    "GrayBrick": {"macro": (0.24, 0.30), "micro": (3.1, 2.8), "streak": (0.18, 3.6), "noise": 2.0, "variation": 0.20, "tint": (0.90, 0.88, 0.80), "dirt": (0.18, 0.15, 0.11), "edge": (1.10, 1.06, 0.92), "grime": 0.32, "streak_strength": 0.17, "edge_strength": 0.16, "roughness": 1.04, "ao": 0.86, "height": 0.042, "specular": 0.36, "clearcoat": 0.0},
    "StoneFoundation": {"macro": (0.30, 0.34), "micro": (2.8, 2.8), "streak": (0.20, 3.1), "noise": 2.2, "variation": 0.16, "tint": (1.00, 0.92, 0.78), "dirt": (0.26, 0.19, 0.12), "edge": (1.10, 1.02, 0.84), "grime": 0.25, "streak_strength": 0.12, "edge_strength": 0.18, "roughness": 1.03, "ao": 0.88, "height": 0.040, "specular": 0.37, "clearcoat": 0.0},
    "AgedWood": {"macro": (0.48, 0.62), "micro": (3.7, 2.1), "streak": (0.30, 2.0), "noise": 2.0, "variation": 0.16, "tint": (1.06, 0.74, 0.48), "dirt": (0.15, 0.07, 0.035), "edge": (1.18, 0.82, 0.55), "grime": 0.22, "streak_strength": 0.15, "edge_strength": 0.14, "roughness": 0.98, "ao": 0.90, "height": 0.026, "specular": 0.34, "clearcoat": 0.0},
    "GateWood": {"macro": (0.55, 0.70), "micro": (4.0, 2.4), "streak": (0.25, 2.2), "noise": 2.3, "variation": 0.18, "tint": (1.12, 0.62, 0.30), "dirt": (0.10, 0.035, 0.018), "edge": (1.24, 0.74, 0.35), "grime": 0.20, "streak_strength": 0.13, "edge_strength": 0.16, "roughness": 0.96, "ao": 0.91, "height": 0.030, "specular": 0.34, "clearcoat": 0.0},
    "DarkTimber": {"macro": (0.44, 0.58), "micro": (3.8, 2.1), "streak": (0.22, 2.0), "noise": 2.1, "variation": 0.17, "tint": (0.84, 0.44, 0.20), "dirt": (0.045, 0.018, 0.008), "edge": (1.16, 0.65, 0.28), "grime": 0.24, "streak_strength": 0.14, "edge_strength": 0.15, "roughness": 0.97, "ao": 0.90, "height": 0.028, "specular": 0.33, "clearcoat": 0.0},
    "ClayRoof": {"macro": (0.28, 0.34), "micro": (3.0, 3.0), "streak": (0.16, 3.2), "noise": 2.2, "variation": 0.18, "tint": (0.64, 0.70, 0.72), "dirt": (0.075, 0.065, 0.055), "edge": (0.76, 0.82, 0.84), "grime": 0.26, "streak_strength": 0.16, "edge_strength": 0.12, "roughness": 0.96, "ao": 0.89, "height": 0.034, "specular": 0.36, "clearcoat": 0.07},
    "ClayRoofTile": {"macro": (0.30, 0.36), "micro": (3.2, 3.0), "streak": (0.17, 3.4), "noise": 2.3, "variation": 0.19, "tint": (0.72, 0.76, 0.78), "dirt": (0.060, 0.052, 0.045), "edge": (0.86, 0.88, 0.86), "grime": 0.28, "streak_strength": 0.18, "edge_strength": 0.13, "roughness": 0.95, "ao": 0.88, "height": 0.036, "specular": 0.35, "clearcoat": 0.08},
    "LimePlaster": {"macro": (0.36, 0.42), "micro": (3.4, 3.2), "streak": (0.18, 3.0), "noise": 2.0, "variation": 0.15, "tint": (1.08, 1.00, 0.80), "dirt": (0.28, 0.22, 0.14), "edge": (1.12, 1.08, 0.90), "grime": 0.24, "streak_strength": 0.16, "edge_strength": 0.13, "roughness": 1.01, "ao": 0.90, "height": 0.032, "specular": 0.35, "clearcoat": 0.0},
    "DarkMetal": {"macro": (0.48, 0.48), "micro": (4.2, 4.2), "streak": (0.24, 2.6), "noise": 2.8, "variation": 0.12, "tint": (0.72, 0.78, 0.84), "dirt": (0.055, 0.045, 0.035), "edge": (0.95, 0.98, 1.02), "grime": 0.18, "streak_strength": 0.10, "edge_strength": 0.24, "roughness": 0.92, "ao": 0.93, "height": 0.022, "specular": 0.48, "clearcoat": 0.0},
    "BlackIron": {"macro": (0.50, 0.50), "micro": (4.4, 4.4), "streak": (0.22, 2.8), "noise": 2.6, "variation": 0.12, "tint": (0.74, 0.80, 0.84), "dirt": (0.040, 0.032, 0.026), "edge": (0.94, 0.98, 1.02), "grime": 0.16, "streak_strength": 0.10, "edge_strength": 0.26, "roughness": 0.91, "ao": 0.93, "height": 0.024, "specular": 0.50, "clearcoat": 0.0},
    "Plaque": {"macro": (0.55, 0.55), "micro": (2.6, 2.6), "streak": (0.24, 2.4), "noise": 1.8, "variation": 0.12, "tint": (1.10, 0.86, 0.48), "dirt": (0.20, 0.11, 0.035), "edge": (1.16, 0.94, 0.62), "grime": 0.16, "streak_strength": 0.08, "edge_strength": 0.20, "roughness": 0.84, "ao": 0.92, "height": 0.020, "specular": 0.46, "clearcoat": 0.16},
    "GatePlaque": {"macro": (0.55, 0.55), "micro": (2.7, 2.7), "streak": (0.24, 2.4), "noise": 1.8, "variation": 0.12, "tint": (1.12, 0.88, 0.52), "dirt": (0.20, 0.11, 0.035), "edge": (1.18, 0.96, 0.66), "grime": 0.16, "streak_strength": 0.08, "edge_strength": 0.20, "roughness": 0.84, "ao": 0.92, "height": 0.020, "specular": 0.46, "clearcoat": 0.16},
}


def _asset(path):
    value = unreal.EditorAssetLibrary.load_asset(path)
    assert value, path
    return value


def _expr(material, cls, x, y):
    return unreal.MaterialEditingLibrary.create_material_expression(material, cls, x, y)


def _connect(source, source_output, target, target_input):
    assert unreal.MaterialEditingLibrary.connect_material_expressions(source, source_output, target, target_input), (source, source_output, target, target_input)


def _connect_property(source, source_output, material, property_name):
    assert unreal.MaterialEditingLibrary.connect_material_property(source, source_output, property_name), (source, source_output, property_name)


def _constant(material, value, x, y):
    node = _expr(material, unreal.MaterialExpressionConstant, x, y)
    node.set_editor_property("r", float(value))
    return node


def _color(material, value, x, y):
    node = _expr(material, unreal.MaterialExpressionConstant3Vector, x, y)
    node.set_editor_property("constant", unreal.LinearColor(float(value[0]), float(value[1]), float(value[2]), 1.0))
    return node


def _coord(material, tiling, x, y):
    node = _expr(material, unreal.MaterialExpressionTextureCoordinate, x, y)
    node.set_editor_property("coordinate_index", 0)
    node.set_editor_property("u_tiling", float(tiling[0]))
    node.set_editor_property("v_tiling", float(tiling[1]))
    return node


def _sample(material, texture, uv, sampler, x, y):
    node = _expr(material, unreal.MaterialExpressionTextureSample, x, y)
    node.set_editor_property("texture", texture)
    node.set_editor_property("sampler_type", sampler)
    _connect(uv, "", node, "UVs")
    return node


def _binary(material, cls, left, right, x, y, left_output="", right_output=""):
    node = _expr(material, cls, x, y)
    _connect(left, left_output, node, "A")
    _connect(right, right_output, node, "B")
    return node


def _multiply(material, left, right, x, y, left_output="", right_output=""):
    return _binary(material, unreal.MaterialExpressionMultiply, left, right, x, y, left_output, right_output)


def _add(material, left, right, x, y, left_output="", right_output=""):
    return _binary(material, unreal.MaterialExpressionAdd, left, right, x, y, left_output, right_output)


def _subtract(material, left, right, x, y, left_output="", right_output=""):
    return _binary(material, unreal.MaterialExpressionSubtract, left, right, x, y, left_output, right_output)


def _lerp(material, first, second, alpha, x, y, first_output="", second_output="", alpha_output=""):
    node = _expr(material, unreal.MaterialExpressionLinearInterpolate, x, y)
    _connect(first, first_output, node, "A")
    _connect(second, second_output, node, "B")
    _connect(alpha, alpha_output, node, "Alpha")
    return node


def _saturate(material, source, x, y, source_output=""):
    # UE's material compiler clamps BaseColor/Roughness/Metallic/AO outputs;
    # keeping this helper as an identity avoids a UE 5.5 pin-name difference
    # on MaterialExpressionSaturate while retaining the bounded source masks.
    return source


def _one_minus(material, source, x, y, source_output=""):
    # TextureSample's default output is accepted by scalar material pins in
    # UE 5.5 and is more portable than relying on the optional named R pin.
    return _subtract(material, _constant(material, 1.0, x - 160, y - 80), source, x, y, "", source_output)


def _noise(material, scale, x, y):
    node = _expr(material, unreal.MaterialExpressionNoise, x, y)
    for prop, value in (("scale", scale), ("quality", 2), ("levels", 5), ("output_min", 0.0), ("output_max", 1.0)):
        try:
            node.set_editor_property(prop, value)
        except Exception:
            pass
    return node


def _fresnel(material, x, y):
    node = _expr(material, unreal.MaterialExpressionFresnel, x, y)
    for prop, value in (("exponent", 4.0), ("base_reflect_fraction", 0.04)):
        try:
            node.set_editor_property(prop, value)
        except Exception:
            pass
    return node


def _maps(gate, name):
    prefix = gate["destination"] + "/Textures/"
    if gate["wuxianmen"]:
        prefix += name + "/T_" + name + "_"
        suffix = "_4K"
    else:
        prefix += "T_" + name + "_"
        suffix = ""
    return {channel: _asset(prefix + channel + suffix) for channel in MAPS}


def _build_material(gate, name):
    profile = PROFILES[name]
    materials_dir = gate["destination"] + "/Materials"
    path = materials_dir + "/M_" + name + SUFFIX
    material = _asset(path) if unreal.EditorAssetLibrary.does_asset_exist(path) else unreal.AssetToolsHelpers.get_asset_tools().create_asset("M_" + name + SUFFIX, materials_dir, unreal.Material, unreal.MaterialFactoryNew())
    assert isinstance(material, unreal.Material), path
    lib = unreal.MaterialEditingLibrary
    lib.delete_all_material_expressions(material)
    material.set_editor_property("used_with_nanite", True)
    material.set_editor_property("two_sided", True)
    material.set_editor_property("blend_mode", unreal.BlendMode.BLEND_OPAQUE)
    maps = _maps(gate, name)

    macro_uv = _coord(material, profile["macro"], -1560, -20)
    micro_uv = _coord(material, profile["micro"], -1560, 720)
    streak_uv = _coord(material, profile["streak"], -1560, 1460)
    height_sample = _sample(material, maps["Height"], macro_uv, unreal.MaterialSamplerType.SAMPLERTYPE_MASKS, -1320, 260)
    bump = _expr(material, unreal.MaterialExpressionBumpOffset, -1120, 260)
    _connect(macro_uv, "", bump, "Coordinate")
    _connect(height_sample, "", bump, "Height")
    try:
        bump.set_editor_property("height_ratio", float(profile["height"]))
        bump.set_editor_property("reference_plane", 0.5)
    except Exception:
        pass

    base = _sample(material, maps["BaseColor"], bump, unreal.MaterialSamplerType.SAMPLERTYPE_COLOR, -1320, -300)
    boosted = _multiply(material, base, _constant(material, 1.08, -1320, -100), -1120, -300, "RGB")
    macro = _noise(material, profile["noise"], -1300, 1660)
    macro_range = _lerp(material, _constant(material, 1.0 - profile["variation"], -1080, 1640), _constant(material, 1.0 + profile["variation"], -1080, 1750), macro, -860, 1660)
    macro_color = _multiply(material, boosted, macro_range, -650, -300)
    tinted = _lerp(material, macro_color, _color(material, profile["tint"], -860, -40), _constant(material, 0.14, -860, 80), -420, -300)

    # Cavity/curvature-aware grime mask: authored AO drives the crevice term,
    # while a world-stable procedural noise adds broad breakup.
    ao_source = _sample(material, maps["AO"], bump, unreal.MaterialSamplerType.SAMPLERTYPE_MASKS, -1320, 1140)
    cavity = _one_minus(material, ao_source, -1080, 1140)
    grime_noise = _noise(material, profile["noise"] * 0.62, -1080, 1880)
    cavity_weight = _add(material, _constant(material, 0.20, -860, 1260), _multiply(material, cavity, _constant(material, 1.05, -860, 1370), -650, 1260), -420, 1260)
    grime_mask = _saturate(material, _multiply(material, grime_noise, cavity_weight, -200, 1260), -20, 1260)
    grime_alpha = _multiply(material, grime_mask, _constant(material, profile["grime"], -20, 1380), 210, 1260)
    grime_layer = _lerp(material, tinted, _color(material, profile["dirt"], -420, 120), grime_alpha, 460, -300)

    streak_noise = _noise(material, profile["noise"] * 0.88, -1080, 2100)
    streak_source = _sample(material, maps["BaseColor"], streak_uv, unreal.MaterialSamplerType.SAMPLERTYPE_COLOR, -860, 1460)
    streak_tint = _multiply(material, streak_source, _color(material, profile["dirt"], -620, 1540), -400, 1540, "RGB")
    streak_alpha = _multiply(material, streak_noise, _constant(material, profile["streak_strength"], -420, 1730), 0, 1540)
    streak_layer = _lerp(material, grime_layer, streak_tint, streak_alpha, 700, -300)

    edge_mask = _fresnel(material, -420, 2220)
    edge_alpha = _multiply(material, edge_mask, _constant(material, profile["edge_strength"], -200, 2220), 40, 2220)
    final_base = _lerp(material, streak_layer, _color(material, profile["edge"], 40, 1980), edge_alpha, 930, -300)
    _connect_property(final_base, "", material, unreal.MaterialProperty.MP_BASE_COLOR)

    macro_normal = _sample(material, maps["Normal"], bump, unreal.MaterialSamplerType.SAMPLERTYPE_NORMAL, -1320, 520)
    micro_normal = _sample(material, maps["Normal"], micro_uv, unreal.MaterialSamplerType.SAMPLERTYPE_NORMAL, -1320, 820)
    normal_output = macro_normal
    normal_layers = 1
    blend_class = getattr(unreal, "MaterialExpressionBlendAngleCorrectedNormals", None)
    if blend_class is not None:
        try:
            blend_normals = _expr(material, blend_class, -760, 620)
            _connect(macro_normal, "RGB", blend_normals, "BaseNormal")
            _connect(micro_normal, "RGB", blend_normals, "AdditionalNormal")
            normal_output = blend_normals
            normal_layers = 2
        except Exception as exc:
            unreal.log_warning("Deep AAA angle-normal blend fallback for %s: %s" % (name, exc))
    if normal_layers == 1:
        # The UE 5.5 Python bindings do not expose a connectable input pin for
        # MaterialExpressionNormalize.  A typed additive vector path is the
        # portable option: it retains the authored macro normal and injects a
        # deliberately restrained fine-scale detail layer; the material normal
        # input performs its normal-space handling at compile time.
        normal_output = _add(
            material,
            macro_normal,
            _multiply(material, micro_normal, _constant(material, 0.42, -1040, 760), -880, 760, "RGB"),
            -700,
            620,
            "RGB",
            "",
        )
        normal_layers = 2
    _connect_property(normal_output, "RGB" if normal_output is macro_normal else "", material, unreal.MaterialProperty.MP_NORMAL)

    rough_source = _sample(material, maps["Roughness"], bump, unreal.MaterialSamplerType.SAMPLERTYPE_MASKS, -1320, 900)
    rough_grime = _multiply(material, grime_mask, _constant(material, 0.16, -200, 930), 20, 930)
    rough_base = _multiply(material, rough_source, _constant(material, profile["roughness"], -900, 1020), -650, 900)
    rough_added = _saturate(material, _add(material, rough_base, rough_grime, -420, 900), -180, 900)
    rough_edge_drop = _multiply(material, edge_mask, _constant(material, 0.10, -200, 2340), 40, 2340)
    rough_final = _saturate(material, _subtract(material, rough_added, rough_edge_drop, 250, 900), 440, 900)
    _connect_property(rough_final, "", material, unreal.MaterialProperty.MP_ROUGHNESS)

    metallic = _sample(material, maps["Metallic"], bump, unreal.MaterialSamplerType.SAMPLERTYPE_MASKS, -1320, 1180)
    _connect_property(_saturate(material, metallic, -1040, 1180), "", material, unreal.MaterialProperty.MP_METALLIC)
    ao_final = _lerp(material, _constant(material, 1.0, -860, 1380), ao_source, _constant(material, profile["ao"], -860, 1490), -620, 1140)
    _connect_property(ao_final, "", material, unreal.MaterialProperty.MP_AMBIENT_OCCLUSION)
    _connect_property(_constant(material, profile["specular"], 720, 1100), "", material, unreal.MaterialProperty.MP_SPECULAR)
    if profile["clearcoat"] > 0.0:
        for prop_name, value in (("MP_CLEAR_COAT", profile["clearcoat"]), ("MP_CLEAR_COAT_ROUGHNESS", 0.22)):
            prop = getattr(unreal.MaterialProperty, prop_name, None)
            if prop is not None:
                try:
                    _connect_property(_constant(material, value, 720, 1220), "", material, prop)
                except Exception as exc:
                    unreal.log_warning("Deep AAA optional %s fallback for %s: %s" % (prop_name, name, exc))

    lib.layout_material_expressions(material)
    lib.recompile_material(material)
    assert unreal.EditorAssetLibrary.save_loaded_asset(material, only_if_is_dirty=False), path
    return material, {
        "path": material.get_path_name(),
        "maps": {key: value.get_path_name() for key, value in maps.items()},
        "graph": ["macro authored PBR + procedural breakup", "AO/cavity grime overlay", "stretched streak overlay", "Fresnel edge-wear overlay", "macro+micro additive normal reinforcement (portable UE Python fallback)", "height BumpOffset", "roughness/metallic/AO calibration"],
        "normal_layers": normal_layers,
        "height_ratio": profile["height"],
        "two_sided": True,
        "used_with_nanite": True,
        "clearcoat": profile["clearcoat"],
    }


def _import_detail(gate, materials):
    source = gate["detail_source"]
    assert source.exists(), source
    path = gate["detail_folder"] + "/" + gate["detail_asset_name"] + "." + gate["detail_asset_name"]
    mesh = _asset(path) if unreal.EditorAssetLibrary.does_asset_exist(path) else None
    if mesh is None or gate.get("force_detail_reimport", False):
        task = unreal.AssetImportTask()
        task.filename = str(source)
        task.destination_path = gate["detail_folder"]
        task.destination_name = gate["detail_asset_name"]
        task.automated, task.save, task.replace_existing = True, True, True
        ui = unreal.FbxImportUI()
        ui.import_mesh, ui.import_materials, ui.import_textures = True, False, False
        ui.mesh_type_to_import = unreal.FBXImportType.FBXIT_STATIC_MESH
        ui.automated_import_should_detect_type = False
        ui.static_mesh_import_data.combine_meshes = True
        ui.static_mesh_import_data.generate_lightmap_u_vs = False
        ui.static_mesh_import_data.auto_generate_collision = False
        ui.static_mesh_import_data.build_nanite = True
        task.options = ui
        world = unreal.get_editor_subsystem(unreal.UnrealEditorSubsystem).get_editor_world()
        old_flag = unreal.SystemLibrary.get_console_variable_bool_value("Interchange.FeatureFlags.Import.FBX")
        unreal.SystemLibrary.execute_console_command(world, "Interchange.FeatureFlags.Import.FBX 0")
        try:
            task.factory = unreal.FbxFactory()
            unreal.AssetToolsHelpers.get_asset_tools().import_asset_tasks([task])
        finally:
            unreal.SystemLibrary.execute_console_command(world, "Interchange.FeatureFlags.Import.FBX " + str(int(old_flag)))
        imported = [obj for obj in task.get_objects() if isinstance(obj, unreal.StaticMesh)]
        assert len(imported) == 1, task.imported_object_paths
        mesh = imported[0]
    assert isinstance(mesh, unreal.StaticMesh), path
    static_materials = mesh.get_editor_property("static_materials")
    bound = []
    for index, slot in enumerate(static_materials):
        slot_name = str(slot.material_slot_name)
        name = slot_name[2:] if slot_name.startswith("M_") else slot_name
        assert name in materials, (slot_name, list(materials))
        mesh.set_material(index, materials[name])
        bound.append(slot_name)
    body = mesh.get_editor_property("body_setup")
    try:
        body.set_editor_property("collision_trace_flag", unreal.CollisionTraceFlag.CTF_USE_DEFAULT)
    except Exception:
        pass
    try:
        body.set_editor_property("double_sided_geometry", True)
    except Exception:
        pass
    try:
        nanite = mesh.get_editor_property("nanite_settings")
        nanite.set_editor_property("enabled", True)
        mesh.set_editor_property("nanite_settings", nanite)
    except Exception as exc:
        unreal.log_warning("Deep AAA Nanite property audit fallback: %s" % exc)
    assert unreal.EditorAssetLibrary.save_loaded_asset(mesh, only_if_is_dirty=False), path
    return mesh, bound, path


def _blueprint_components(blueprint):
    subsystem = unreal.get_engine_subsystem(unreal.SubobjectDataSubsystem)
    library = unreal.SubobjectDataBlueprintFunctionLibrary
    result = []
    for handle in subsystem.k2_gather_subobject_data_for_blueprint(blueprint):
        data = subsystem.k2_find_subobject_data_from_handle(handle)
        component = library.get_object(data)
        if isinstance(component, unreal.StaticMeshComponent):
            result.append(component)
    return subsystem, library, result


def _rebind_blueprint(gate, materials, detail_mesh):
    blueprint = _asset(gate["blueprint"])
    subsystem, library, components = _blueprint_components(blueprint)
    rebound = []
    for component in components:
        if "DeepAAA_DetailGeometry" in component.get_name():
            continue
        if not component.static_mesh:
            continue
        changed = []
        for index, slot in enumerate(component.static_mesh.get_editor_property("static_materials")):
            slot_name = str(slot.material_slot_name)
            name = slot_name[2:] if slot_name.startswith("M_") else slot_name
            if name in materials:
                component.set_material(index, materials[name])
                changed.append(slot_name)
        if changed:
            rebound.append({"component": component.get_name(), "mesh": component.static_mesh.get_path_name(), "slots": changed})

    detail_component = next((component for component in components if "DeepAAA_DetailGeometry" in component.get_name()), None)
    if detail_component is None:
        handles = subsystem.k2_gather_subobject_data_for_blueprint(blueprint)
        root = next((handle for handle in handles if library.is_root_component(subsystem.k2_find_subobject_data_from_handle(handle))), None)
        assert root, gate["blueprint"]
        params = unreal.AddNewSubobjectParams(parent_handle=root, new_class=unreal.StaticMeshComponent, blueprint_context=blueprint, conform_transform_to_parent=False)
        handle, reason = subsystem.add_new_subobject(params)
        assert library.is_handle_valid(handle), str(reason)
        subsystem.rename_subobject(handle, unreal.Text("DeepAAA_DetailGeometry"))
        detail_component = library.get_object(subsystem.k2_find_subobject_data_from_handle(handle))
    detail_component.set_static_mesh(detail_mesh)
    detail_component.set_editor_property("relative_location", unreal.Vector(0.0, 0.0, 0.0))
    detail_component.set_editor_property("relative_rotation", unreal.Rotator(roll=gate["detail_rotation"]))
    detail_component.set_editor_property("relative_scale3d", unreal.Vector(1.0, 1.0, 1.0))
    detail_component.set_editor_property("mobility", unreal.ComponentMobility.STATIC)
    detail_component.set_collision_profile_name("NoCollision")
    detail_component.set_editor_property("visible", True)
    detail_component.set_editor_property("hidden_in_game", False)
    detail_component.set_editor_property("cast_shadow", True)
    for index, slot in enumerate(detail_mesh.get_editor_property("static_materials")):
        slot_name = str(slot.material_slot_name)
        name = slot_name[2:] if slot_name.startswith("M_") else slot_name
        if name in materials:
            detail_component.set_material(index, materials[name])
    try:
        detail_component.set_editor_property("component_tags", ["AAADeepGeometry", "RollbackSafeAdditive"])
    except Exception:
        pass
    unreal.BlueprintEditorLibrary.compile_blueprint(blueprint)
    assert unreal.EditorAssetLibrary.save_loaded_asset(blueprint, only_if_is_dirty=False), gate["blueprint"]
    rebound.append({"component": detail_component.get_name(), "mesh": detail_mesh.get_path_name(), "slots": [str(slot.material_slot_name) for slot in detail_mesh.get_editor_property("static_materials")]})
    return blueprint, rebound, detail_component.get_name()


def _run_gate(label, gate):
    dirty_maps = unreal.EditorLoadingAndSavingUtils.get_dirty_map_packages()
    if dirty_maps:
        # Blueprint/material saves do not require a map save.  Keep any
        # unrelated preview-level edits untouched and make the no-map-write
        # decision explicit in the live log.
        unreal.log_warning("Deep AAA preserving dirty map packages without saving: %s" % [str(package) for package in dirty_maps])
    manifest = json.loads(gate["detail_manifest"].read_text(encoding="utf-8"))
    materials, material_records = {}, {}
    for name in gate["material_names"]:
        material, record = _build_material(gate, name)
        materials[name] = material
        material_records[name] = record
    detail_mesh, detail_slots, detail_path = _import_detail(gate, materials)
    blueprint, rebound, detail_component_name = _rebind_blueprint(gate, materials, detail_mesh)
    result = {
        "intent": "Deep AAA materials plus additive hero geometry for " + label,
        "variant_suffix": SUFFIX,
        "blueprint": gate["blueprint"],
        "materials": material_records,
        "detail_mesh": detail_path,
        "detail_source": manifest,
        "detail_slots": detail_slots,
        "blueprint_component_count_rebound": len(rebound),
        "blueprint_material_components_rebound": len([row for row in rebound if row["component"] != detail_component_name]),
        "detail_component": detail_component_name,
        "detail_component_relative_rotation_roll": gate["detail_rotation"],
        "geometry_changed": True,
        "uvs_changed": False,
        "collision_changed": False,
        "placement_changed": False,
        "detail_collision_intent": "NoCollision additive component; source Blueprint collision and collision intent preserved",
        "rollback_assets": [gate["destination"] + "/Materials/M_" + name + suffix for name in gate["material_names"] for suffix in gate["rollback_suffixes"]],
    }
    report_path = ROOT / (label + "_V4-deep-aaa.json")
    report_path.write_text(json.dumps(result, indent=2), encoding="utf-8")
    print("GUANGZHOU_DEEP_AAA_APPLIED", json.dumps({"gate": label, "materials": len(material_records), "detail_triangles": manifest["triangle_count"], "rebound_components": len(rebound), "report": str(report_path)}))


def main():
    for label, gate in GATES.items():
        _run_gate(label, gate)


if __name__ == "__main__":
    main()
