"""Import and apply the Zhengnanmen high-poly GLB in place.

The existing Great South Gate asset is left untouched.  A versioned mesh and
its imported materials/textures are created beside it, then the one existing
showcase actor is retargeted while retaining its actor identity, label, tags,
rotation, and scale.  Translation is recomputed only as needed to keep the
published placement center and terrain contact stable when the replacement
mesh has a different local origin.
"""
import json
import re
from pathlib import Path

import unreal


PROJECT_ROOT = Path("C:/Git/AuraProj")
SOURCE = Path("C:/Works/RawModel3D/GreatSouthGate_Zhengnanmen_UE5_HighPoly.glb")
if not SOURCE.exists():
    SOURCE = Path("C:/Works/Raw3DModels/GreatSouthGate_Zhengnanmen_UE5_HighPoly.glb")

LEVEL_PATH = "/Game/Scifi_desert_city/Level/L_showcase_level"
DEST = "/Game/Assets/Environment/GuangzhouLandmarks/GreatSouthGate_Zhengnanmen_HighPoly"
NEW_ASSET = DEST + "/SM_GreatSouthGate_Zhengnanmen_HighPoly"
OLD_ASSET = "/Game/Assets/Environment/GuangzhouLandmarks/GreatSouthGate/SM_GreatSouthGate"
REPORT_PATH = PROJECT_ROOT / "Saved/RawModelImport/GreatSouthGateZhengnanmen.json"
PLACEMENT_MANIFEST = PROJECT_ROOT / "Saved/RawModelImport/guangzhou-landmark-placement.json"
ACTOR_LABEL = "GuangzhouLandmark_GreatSouthGate"
ACTOR_TAG = "ImportedGuangzhouLandmark"

assert PROJECT_ROOT.resolve() == Path(
    unreal.Paths.convert_relative_path_to_full(unreal.Paths.project_dir())
).resolve(), "Wrong Unreal project"
assert SOURCE.exists(), SOURCE
assert PLACEMENT_MANIFEST.exists(), PLACEMENT_MANIFEST


def mesh_bounds(mesh):
    bounds = mesh.get_bounds()
    return {
        "origin_cm": [bounds.origin.x, bounds.origin.y, bounds.origin.z],
        "size_cm": [
            bounds.box_extent.x * 2.0,
            bounds.box_extent.y * 2.0,
            bounds.box_extent.z * 2.0,
        ],
        "bottom_z_cm": bounds.origin.z - bounds.box_extent.z,
        "max_z_cm": bounds.origin.z + bounds.box_extent.z,
    }


def discover_imported_objects():
    registry = unreal.AssetRegistryHelpers.get_asset_registry()
    registry.scan_paths_synchronous([DEST], True)
    assets = []
    for path in unreal.EditorAssetLibrary.list_assets(
        DEST, recursive=True, include_folder=False
    ):
        asset = unreal.EditorAssetLibrary.load_asset(path)
        if asset:
            assets.append(asset)
    return assets


def import_mesh():
    existing = unreal.EditorAssetLibrary.load_asset(NEW_ASSET)
    if existing:
        assert isinstance(existing, unreal.StaticMesh), NEW_ASSET
        return existing, False, discover_imported_objects()

    pipeline = unreal.InterchangeGenericAssetsPipeline()
    pipeline.asset_name = "SM_GreatSouthGate_Zhengnanmen_HighPoly"
    # The source GLB includes an explicit UE-facing root rotation.  Do not add
    # the legacy -90-degree import offset used by the older source asset.
    pipeline.import_offset_uniform_scale = 1.0
    pipeline.common_meshes_properties.bake_meshes = True
    pipeline.mesh_pipeline.combine_static_meshes = True
    pipeline.mesh_pipeline.build_nanite = True
    # Avoid a low-quality autogenerated proxy for this architectural mesh;
    # the post-import pass below requests complex-as-simple when supported.
    pipeline.mesh_pipeline.set_editor_property("collision", False)
    pipeline.mesh_pipeline.generate_lightmap_u_vs = False

    params = unreal.ImportAssetParameters()
    params.is_automated = True
    params.replace_existing = False
    params.override_pipelines = [unreal.SoftObjectPath(pipeline.get_path_name())]
    manager = unreal.InterchangeManager.get_interchange_manager_scripted()
    objects = manager.import_asset(
        DEST, manager.create_source_data(str(SOURCE)), params
    )
    assert objects, "Import returned no objects"
    mesh_objects = [obj for obj in objects if isinstance(obj, unreal.StaticMesh)]
    assert len(mesh_objects) == 1, [obj.get_path_name() for obj in objects]
    mesh = mesh_objects[0]
    assert mesh.get_path_name().startswith(NEW_ASSET + "."), mesh.get_path_name()
    assert unreal.EditorAssetLibrary.save_directory(DEST), "Asset save failed"
    return mesh, True, discover_imported_objects()


def texture_index(texture):
    match = re.search(r"(?:texture|Texture)[_ ]?(\d+)$", texture.get_name())
    return int(match.group(1)) if match else None


def texture_map(assets):
    textures = [asset for asset in assets if isinstance(asset, unreal.Texture2D)]
    indexed = {texture_index(texture): texture for texture in textures}
    if len(indexed) < 10:
        # Interchange may normalize the embedded image names differently.  A
        # stable lexical fallback still preserves the GLB image order when the
        # destination folder was empty at import time.
        ordered = sorted(textures, key=lambda texture: texture.get_path_name())
        indexed = {index: texture for index, texture in enumerate(ordered)}
    assert len(indexed) >= 10, [texture.get_path_name() for texture in textures]
    return indexed


def texture_sample(material, texture, x, y, color=False, normal=False):
    texture.set_editor_property("srgb", color)
    texture.set_editor_property(
        "compression_settings",
        unreal.TextureCompressionSettings.TC_NORMALMAP
        if normal
        else unreal.TextureCompressionSettings.TC_DEFAULT
        if color
        else unreal.TextureCompressionSettings.TC_MASKS,
    )
    if normal:
        texture.set_editor_property("flip_green_channel", True)
    node = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionTextureSample, x, y
    )
    node.texture = texture
    node.sampler_type = (
        unreal.MaterialSamplerType.SAMPLERTYPE_NORMAL
        if normal
        else unreal.MaterialSamplerType.SAMPLERTYPE_COLOR
        if color
        else unreal.MaterialSamplerType.SAMPLERTYPE_MASKS
    )
    return node


def constant_color(material, color, x, y):
    node = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionConstant3Vector, x, y
    )
    node.constant = unreal.LinearColor(*color)
    return node


def constant_value(material, value, x, y):
    node = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionConstant, x, y
    )
    node.r = value
    return node


def rebuild_material(material, textures):
    name = material.get_name()
    unreal.MaterialEditingLibrary.delete_all_material_expressions(material)
    material.set_editor_property("used_with_nanite", True)
    library = unreal.MaterialEditingLibrary

    textured_specs = {
        "M_Stone_PBR_2K": (0, 1, 2, (1.0, 1.0, 1.0, 1.0)),
        "M_DarkWood_PBR_2K": (3, 4, 5, (1.0, 1.0, 1.0, 1.0)),
        "M_RedLacquerWood_PBR_2K": (3, 4, 5, (1.12, 0.68, 0.58, 1.0)),
        "M_GreenGlazedTile_PBR_2K": (6, 7, 8, (1.0, 1.0, 1.0, 1.0)),
    }
    if name in textured_specs:
        base_index, normal_index, orm_index, _ = textured_specs[name]
        base = texture_sample(material, textures[base_index], -500, 0, color=True)
        normal = texture_sample(material, textures[normal_index], -500, 220, normal=True)
        orm = texture_sample(material, textures[orm_index], -500, 440)
        assert library.connect_material_property(
            base, "RGB", unreal.MaterialProperty.MP_BASE_COLOR
        )
        assert library.connect_material_property(
            normal, "RGB", unreal.MaterialProperty.MP_NORMAL
        )
        assert library.connect_material_property(
            orm, "G", unreal.MaterialProperty.MP_ROUGHNESS
        )
        assert library.connect_material_property(
            orm, "B", unreal.MaterialProperty.MP_METALLIC
        )
        assert library.connect_material_property(
            orm, "R", unreal.MaterialProperty.MP_AMBIENT_OCCLUSION
        )
    elif name == "M_Sign_Zhengnanmen":
        base = texture_sample(material, textures[9], -500, 0, color=True)
        assert library.connect_material_property(
            base, "RGB", unreal.MaterialProperty.MP_BASE_COLOR
        )
        roughness = constant_value(material, 0.58, -500, 220)
        metallic = constant_value(material, 0.06, -500, 440)
        assert library.connect_material_property(
            roughness, "", unreal.MaterialProperty.MP_ROUGHNESS
        )
        assert library.connect_material_property(
            metallic, "", unreal.MaterialProperty.MP_METALLIC
        )
    else:
        constants = {
            "M_DarkInterior": ((0.045, 0.035, 0.028, 1.0), 0.92, 0.0),
            "M_AgedGold": ((0.72, 0.45, 0.11, 1.0), 0.34, 0.82),
            "M_Bronze": ((0.40, 0.20, 0.07, 1.0), 0.40, 0.75),
        }
        assert name in constants, name
        color, roughness_value, metallic_value = constants[name]
        color_node = constant_color(material, color, -500, 0)
        roughness = constant_value(material, roughness_value, -500, 220)
        metallic = constant_value(material, metallic_value, -500, 440)
        assert library.connect_material_property(
            color_node, "", unreal.MaterialProperty.MP_BASE_COLOR
        )
        assert library.connect_material_property(
            roughness, "", unreal.MaterialProperty.MP_ROUGHNESS
        )
        assert library.connect_material_property(
            metallic, "", unreal.MaterialProperty.MP_METALLIC
        )
    library.recompile_material(material)


mesh, imported_this_run, imported_assets = import_mesh()
textures = texture_map(imported_assets)
material_names = [
    "M_Stone_PBR_2K",
    "M_DarkWood_PBR_2K",
    "M_RedLacquerWood_PBR_2K",
    "M_GreenGlazedTile_PBR_2K",
    "M_DarkInterior",
    "M_AgedGold",
    "M_Bronze",
    "M_Sign_Zhengnanmen",
]
materials = []
for material_name in material_names:
    material = unreal.EditorAssetLibrary.load_asset(DEST + "/" + material_name)
    assert isinstance(material, unreal.Material), material_name
    rebuild_material(material, textures)
    unreal.EditorAssetLibrary.save_loaded_asset(material)
    materials.append(material)

collision = "not_generated_for_decorative_nanite_mesh"
nanite = True
num_lods = "Nanite-only import; traditional LOD query deferred until editor async build is idle"

loaded = unreal.get_editor_subsystem(unreal.LevelEditorSubsystem).load_level(LEVEL_PATH)
world = (
    unreal.get_editor_subsystem(unreal.UnrealEditorSubsystem).get_editor_world()
    if loaded
    else None
)
assert world, LEVEL_PATH
placement = json.loads(PLACEMENT_MANIFEST.read_text(encoding="utf-8"))
entry = next(item for item in placement["actors"] if item["label"] == ACTOR_LABEL)
actors = unreal.get_editor_subsystem(unreal.EditorActorSubsystem).get_all_level_actors()
matches = [
    actor
    for actor in actors
    if actor.get_actor_label() == ACTOR_LABEL
    and ACTOR_TAG in [str(tag) for tag in actor.tags]
]
assert len(matches) == 1, "Expected one existing Great South Gate actor"
actor = matches[0]
component = actor.get_component_by_class(unreal.StaticMeshComponent)
assert component and component.static_mesh, ACTOR_LABEL
assert (
    component.static_mesh.get_path_name().startswith(OLD_ASSET + ".")
    or component.static_mesh.get_path_name().startswith(NEW_ASSET + ".")
), component.static_mesh.get_path_name()

old_location = actor.get_actor_location()
old_rotation = actor.get_actor_rotation()
old_scale = actor.get_actor_scale3d()
old_mesh_path = component.static_mesh.get_path_name()
old_tags = [str(tag) for tag in actor.tags]

# Keep rotation and scale exactly.  Use the placed actor bounds after assigning
# the mesh to correct only the translation needed to preserve the published
# center and terrain contact; this is the same minimal-origin compensation used
# by the earlier landmark reimport workflow.
component.set_editor_property("static_mesh", mesh)
target_x, target_y = entry["center_xy"]
target_ground = entry["ground_z"]
actor_origin, actor_extent = actor.get_actor_bounds(False)
current_center = unreal.Vector(
    actor_origin.x,
    actor_origin.y,
    actor_origin.z - actor_extent.z,
)
new_location = unreal.Vector(
    old_location.x + (target_x - current_center.x),
    old_location.y + (target_y - current_center.y),
    old_location.z + (target_ground - current_center.z),
)
actor.set_actor_location(new_location, False, True)
actor.set_actor_rotation(old_rotation, False)
actor.set_actor_scale3d(old_scale)
actor.tags = [unreal.Name(tag) for tag in old_tags]
actor.modify()

assert unreal.EditorLoadingAndSavingUtils.save_map(world, LEVEL_PATH), (
    "Failed to save updated showcase level"
)

actor_origin, actor_extent = actor.get_actor_bounds(False)
actor_bounds = {
    "min": [
        actor_origin.x - actor_extent.x,
        actor_origin.y - actor_extent.y,
        actor_origin.z - actor_extent.z,
    ],
    "max": [
        actor_origin.x + actor_extent.x,
        actor_origin.y + actor_extent.y,
        actor_origin.z + actor_extent.z,
    ],
}
report = {
    "source": str(SOURCE),
    "source_bytes": SOURCE.stat().st_size,
    "level": LEVEL_PATH,
    "actor": actor.get_name(),
    "label": actor.get_actor_label(),
    "previous_mesh": old_mesh_path,
    "legacy_mesh": OLD_ASSET,
    "new_mesh": NEW_ASSET,
    "imported_this_run": imported_this_run,
    "previous_location": [old_location.x, old_location.y, old_location.z],
    "location": [new_location.x, new_location.y, new_location.z],
    "rotation": [old_rotation.roll, old_rotation.pitch, old_rotation.yaw],
    "scale": [old_scale.x, old_scale.y, old_scale.z],
    "tags": old_tags,
    "actor_bounds": actor_bounds,
    "mesh_bounds": "deferred_until_editor_async_build_is_idle",
    "material_slots": [material.get_path_name() for material in materials],
    "textures": {
        str(index): texture.get_path_name() for index, texture in sorted(textures.items())
    },
    "nanite": bool(nanite),
    "num_lods": num_lods,
    "collision": collision,
    "transform_preserved": {
        "actor_identity": True,
        "label": True,
        "tags": True,
        "rotation": True,
        "scale": True,
        "translation_regrounded": True,
    },
    "passed": True,
}
REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
REPORT_PATH.write_text(json.dumps(report, indent=2), encoding="utf-8")
print("GREAT_SOUTH_GATE_ZHENGNANMEN_IMPORTED", json.dumps(report))
